[lib]
proc-macro = true

[package]
name = "indexer-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
serde = { version="1.0.203", features = ["derive"] }
serde_json = "1.0.117"
syn = { version="2.0.66", features = ["full"] }
